TrainingArguments:
  num_train_epochs: 10
  warmup_steps: 500
  per_device_train_batch_size: 1
  weight_decay: 0.01
  loggin_steps: 10
  evaluation_strategy: steps
  eval_steps: 500
  save_steps: 1e6
  gradient_accumulation_step: 16 