TrainingArguments:
  num_train_epochs: 3
  warmup_steps: 500
  eval_steps: 1000
  learning_rate: 5e-5
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 2
  weight_decay: 0.01
  evaluation_strategy: "steps"
  logging_steps: 100
  save_steps: 1000
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  fp16: true
  report_to:
    - "tensorboard"

# TrainingArguments:
#   num_train_epochs: 1
#   warmup_steps: 500
#   per_device_train_batch_size: 8
#   weight_decay: 0.01
#   logging_steps: 10
#   evaluation_strategy: steps
#   eval_steps: 500
#   save_steps: 1e6
#   gradient_accumulation_steps: 16 