artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  # source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  source_URL: https://drive.google.com/uc?export=download&id=147ZEGcDjYnfpJCCET1WpTmbqi8iZVotG
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train","test","validation"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/summary_data
  # TOKENIZER: google/pegasus-cnn_dailymail
  TOKENIZER: sshleifer/distilbart-cnn-12-6

model_trainer:
  root_dir: artifacts/model
  data_path: artifacts/data_transformation/summary_data
  # model_ckpt: google/pegasus-cnn_dailymail
  model_ckpt: sshleifer/distilbart-cnn-12-6
  
model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/summary_data
  model_path: artifacts/model/distilbart_model_01
  tokenizer_path: artifacts/model/distilbart_tokenizer_01
  metric_file: artifacts/model_evaluation/metrics.csv
